/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-05-14 16:21:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class tourismIntroduction_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1651028845361L));
    _jspx_dependants.put("jar:file:/D:/PicnicProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PicnicProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>PestKit - Pest Control Website Template</title>\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("<meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Google Web Fonts -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Nunito:wght@600;700;800&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!--         Icon Font Stylesheet -->\r\n");
      out.write("<!--         <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\"> -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!--         Libraries Stylesheet -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/animate/animate.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/owlcarousel/assets/owl.carousel.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/img.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Template Stylesheet -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/tourismintroduction.css\"\r\n");
      out.write("	rel=\"tourismintroduction\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Spinner Start -->\r\n");
      out.write("	<div id=\"spinner\"\r\n");
      out.write("		class=\"show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50 d-flex align-items-center justify-content-center\">\r\n");
      out.write("		<div class=\"spinner-grow text-primary\" role=\"status\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Topbar Start -->\r\n");
      out.write("	<div class=\"container-fluid topbar-top bg-primary\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"d-flex justify-content-between topbar py-2\">\r\n");
      out.write("				<div class=\"d-flex align-items-center flex-shrink-0 topbar-info\">\r\n");
      out.write("					<a href=\"#\" class=\"me-4 text-secondary\"><i\r\n");
      out.write("						class=\"fas fa-map-marker-alt me-2 text-dark\"></i>123 Street, CA,\r\n");
      out.write("						USA</a> <a href=\"#\" class=\"me-4 text-secondary\"><i\r\n");
      out.write("						class=\"fas fa-phone-alt me-2 text-dark\"></i>+01234567890</a> <a\r\n");
      out.write("						href=\"#\" class=\"text-secondary\"><i\r\n");
      out.write("						class=\"fas fa-envelope me-2 text-dark\"></i>Example@gmail.com</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"text-end pe-4 me-4 border-end border-dark search-btn\">\r\n");
      out.write("					<div class=\"search-form\">\r\n");
      out.write("						<form method=\"post\" action=\"index.html\">\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<div class=\"d-flex\">\r\n");
      out.write("									<input type=\"search\" class=\"form-control border-0 rounded-pill\"\r\n");
      out.write("										name=\"search-input\" value=\"\" placeholder=\"Search Here\"\r\n");
      out.write("										required=\"\" />\r\n");
      out.write("									<button type=\"submit\" value=\"Search Now!\" class=\"btn\">\r\n");
      out.write("										<i class=\"fa fa-search text-dark\"></i>\r\n");
      out.write("									</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"d-flex align-items-center justify-content-center topbar-icon\">\r\n");
      out.write("						<a href=\"#\" class=\"me-4\"><i\r\n");
      out.write("							class=\"fab fa-facebook-f text-dark\"></i></a> <a href=\"#\" class=\"me-4\"><i\r\n");
      out.write("							class=\"fab fa-twitter text-dark\"></i></a> <a href=\"#\" class=\"me-4\"><i\r\n");
      out.write("							class=\"fab fa-instagram text-dark\"></i></a> <a href=\"#\" class=\"\"><i\r\n");
      out.write("							class=\"fab fa-linkedin-in text-dark\"></i></a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Topbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Navbar Start -->\r\n");
      out.write("		<div class=\"container-fluid bg-dark\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<nav class=\"navbar navbar-dark navbar-expand-lg py-lg-0\">\r\n");
      out.write("					<a href=\"index.html\" class=\"navbar-brand\">\r\n");
      out.write("						<h1 class=\"text-primary mb-0 display-5\">\r\n");
      out.write("							나들이<i class=\"fa fa-spider text-primary ms-2\"></i>\r\n");
      out.write("						</h1>\r\n");
      out.write("					</a>\r\n");
      out.write("					<button class=\"navbar-toggler bg-primary\" type=\"button\"\r\n");
      out.write("						data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("						<span class=\"fa fa-bars text-dark\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<div class=\"collapse navbar-collapse me-n3\" id=\"navbarCollapse\">\r\n");
      out.write("						<div class=\"navbar-nav ms-auto\">\r\n");
      out.write("							<a href=\"index.html\" class=\"nav-item nav-link\">Home</a> <a\r\n");
      out.write("								href=\"about.html\" class=\"nav-item nav-link\">About</a> <a\r\n");
      out.write("								href=\"service.html\" class=\"nav-item nav-link\">Services</a> <a\r\n");
      out.write("								href=\"project.html\" class=\"nav-item nav-link\">Projects</a>\r\n");
      out.write("							<div class=\"nav-item dropdown\">\r\n");
      out.write("								<a href=\"#\" class=\"nav-link dropdown-toggle\"\r\n");
      out.write("									data-bs-toggle=\"dropdown\">Pages</a>\r\n");
      out.write("								<div class=\"dropdown-menu m-0 bg-primary\">\r\n");
      out.write("									<a href=\"price.html\" class=\"dropdown-item\">Pricing Plan</a> <a\r\n");
      out.write("										href=\"blog.html\" class=\"dropdown-item\">Blog Post</a> <a\r\n");
      out.write("										href=\"team.html\" class=\"dropdown-item\">Team Members</a> <a\r\n");
      out.write("										href=\"testimonial.html\" class=\"dropdown-item\">Testimonial</a>\r\n");
      out.write("									<a href=\"404.html\" class=\"dropdown-item\">404 Page</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<a href=\"contact.html\" class=\"nav-item nav-link active\">Contact</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!--페이지 헤더 -->\r\n");
      out.write("		<div class=\"container-fluid page-header py-5\">\r\n");
      out.write("			<div class=\"container text-center py-5\">\r\n");
      out.write("				<h1 class=\"display-2 text-white mb-4 animated slideInDown\">Contact</h1>\r\n");
      out.write("				<nav aria-label=\"breadcrumb\">\r\n");
      out.write("					<ol\r\n");
      out.write("						class=\"breadcrumb justify-content-center mb-0 animated slideInDown\">\r\n");
      out.write("						<li class=\"breadcrumb-item\"><a href=\"/\">Home</a></li>\r\n");
      out.write("						<li class=\"breadcrumb-item\"><a href=\"tourismIntroduction\">관광지소개</a></li>\r\n");
      out.write("						<li class=\"breadcrumb-item text-white\" aria-current=\"page\">Contact</li>\r\n");
      out.write("					</ol>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Page Header End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Copyright Start, 하단 부분-->\r\n");
      out.write("		<!--         <div class=\"container-fluid copyright bg-dark py-4\"> -->\r\n");
      out.write("		<!--             <div class=\"container\"> -->\r\n");
      out.write("		<!--                 <div class=\"row\"> -->\r\n");
      out.write("		<!--                     <div class=\"col-md-4 text-center text-md-start mb-3 mb-md-0\"> -->\r\n");
      out.write("		<!--                         <a href=\"#\" class=\"text-primary mb-0 display-6\">Pest<span class=\"text-white\">Kit</span><i class=\"fa fa-spider text-primary ms-2\"></i></a> -->\r\n");
      out.write("		<!--                     </div> -->\r\n");
      out.write("		<!--                     <div class=\"col-md-4 copyright-btn text-center text-md-start mb-3 mb-md-0 flex-shrink-0\"> -->\r\n");
      out.write("		<!--                         <a class=\"btn btn-primary rounded-circle me-3 copyright-icon\" href=\"\"><i class=\"fab fa-twitter\"></i></a> -->\r\n");
      out.write("		<!--                         <a class=\"btn btn-primary rounded-circle me-3 copyright-icon\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a> -->\r\n");
      out.write("		<!--                         <a class=\"btn btn-primary rounded-circle me-3 copyright-icon\" href=\"\"><i class=\"fab fa-youtube\"></i></a> -->\r\n");
      out.write("		<!--                         <a class=\"btn btn-primary rounded-circle me-3 copyright-icon\" href=\"\"><i class=\"fab fa-linkedin-in\"></i></a> -->\r\n");
      out.write("		<!--                     </div> -->\r\n");
      out.write("		<!--                     <div class=\"col-md-4 my-auto text-center text-md-end text-white\"> -->\r\n");
      out.write("		<!--                         /*** This template is free as long as you keep the below author’s credit link/attribution link/backlink. ***/ -->\r\n");
      out.write("		<!--                         /*** If you'd like to use the template without the below author’s credit link/attribution link/backlink, ***/ -->\r\n");
      out.write("		<!--                         /*** you can purchase the Credit Removal License from \"https://htmlcodex.com/credit-removal\". ***/ -->\r\n");
      out.write("		<!--                         Designed By <a class=\"border-bottom\" href=\"https://htmlcodex.com\">HTML Codex</a><br>Distributed By <a class=\"border-bottom\" href=\"https://themewagon.com\">ThemeWagon</a> -->\r\n");
      out.write("		<!--                     </div> -->\r\n");
      out.write("		<!--                 </div> -->\r\n");
      out.write("		<!--             </div> -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Copyright End -->\r\n");
      out.write("\r\n");
      out.write("	<form method=\"get\" action=\"SelectServlet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"entire-region container\">\r\n");
      out.write("			<div class=\"dropdown dropdown_button\">\r\n");
      out.write("				<!-- 			<a href=\"#\" class=\"nav-link dropdown-toggle\" -->\r\n");
      out.write("				<!-- 				data-bs-toggle=\"dropdown\">지역별 전체보기</a> -->\r\n");
      out.write("				<a href=\"#\" class=\"dropdown-toggle dropdown_font\" data-bs-toggle=\"dropdown\">지역별\r\n");
      out.write("					전체보기</a>\r\n");
      out.write("				<div class=\"dropdown-menu m-0 bg-primary\">\r\n");
      out.write("					<a href=\"price.html\" class=\"dropdown-item\">충남</a> <a\r\n");
      out.write("						href=\"blog.html\" class=\"dropdown-item\">충청</a> <a href=\"team.html\"\r\n");
      out.write("						class=\"dropdown-item\">전남</a> <a href=\"testimonial.html\"\r\n");
      out.write("						class=\"dropdown-item\">전라</a> <a href=\"404.html\"\r\n");
      out.write("						class=\"dropdown-item\">404 Page</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"nav-item dropdown dropdown_button\">\r\n");
      out.write("				<a href=\"#\" class=\"dropdown-toggle dropdown_font\" data-bs-toggle=\"dropdown\">상세\r\n");
      out.write("					지역</a>\r\n");
      out.write("				<div class=\"dropdown-menu m-0 bg-primary\">\r\n");
      out.write("					<a href=\"price.html\" class=\"dropdown-item\">예산</a> <a\r\n");
      out.write("						href=\"blog.html\" class=\"dropdown-item\">천안</a> <a href=\"team.html\"\r\n");
      out.write("						class=\"dropdown-item\">홍성</a> <a href=\"testimonial.html\"\r\n");
      out.write("						class=\"dropdown-item\">공주</a> <a href=\"404.html\"\r\n");
      out.write("						class=\"dropdown-item\">404 Page</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"entire-region2 container\">\r\n");
      out.write("			<div class=\"dropdown dropdown_button\">\r\n");
      out.write("				<!-- 			<a href=\"#\" class=\"nav-link dropdown-toggle\" -->\r\n");
      out.write("				<!-- 				data-bs-toggle=\"dropdown\">지역별 전체보기</a> -->\r\n");
      out.write("				<a href=\"#\" class=\"dropdown-toggle dropdown_font\" data-bs-toggle=\"dropdown\">지역별\r\n");
      out.write("					축제정보</a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"nav-item dropdown dropdown_button dropdown_font\">\r\n");
      out.write("				<a href=\"#\" class=\"dropdown-toggle dropdown_font \" data-bs-toggle=\"dropdown\">숙박정보</a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"nav-item dropdown dropdown_button dropdown_font\">\r\n");
      out.write("				<a href=\"#\" class=\"dropdown-toggle dropdown_font \" data-bs-toggle=\"dropdown\">식당정보</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Back to Top, 맨 아래 창에서 버튼을 누르면 위로 올려준다 -->\r\n");
      out.write("	<a href=\"#\" class=\"btn btn-primary rounded-circle border-3 back-to-top\"><i\r\n");
      out.write("		class=\"fa fa-arrow-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- JavaScript Libraries -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/wow/wow.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/easing/easing.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Template Javascript -->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/tourismIntroduction.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/tourismIntroduction.jsp(3,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/tourismIntroduction.jsp(3,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
